repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.12.1
    hooks:
      - id: validate_manifest
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [pep8-naming]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3