version: "3.9"
services:
  vansterdam-app:
    container_name: vansterdam_app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/vansterdam
    environment:
      - DB_HOST=vansterdam_db
      - DB_NAME=vansterdam
      - DB_USER=postgres
      - DB_PASS=password
      - DB_PORT=5432
      - SECRET_KEY=dev-secret-key
    depends_on:
      - vansterdam-db
  vansterdam-db:
    container_name: vansterdam_db
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    volumes:
      - vansterdam-db-volume:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=vansterdam
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  vansterdam-db-volume:
